### ISSUE TITLE
MDF Link Manipulation

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#307]
# Story
Currently, when an MDF is sent out it gives a link in the following format: .../api/mdf/96/pdf/ This opens the door to link manipulation that would allow any user to view all current MDFs, even if they have not been provided the link.

# Possible Solutions
- Use some sort of a hash to turn MDF ids into random strings that would be unpredictable
- Attach the pdf of the MDF directly to the email so that there is no link at all

**Comment by benaduggan** [comment]
Just to document this here since we talked about it in slack directly. We could use a UUID field as a composite or primary key on the MDF so no one could really guess other PDFs. 

If we go the route of attaching the email directly, do you think that could cause issues if the budget is ever updated, but new emails aren't sent out with the updated MDF? If we do that, we might have to send out new copies to people we emailed before, but that would be a pretty big change because we don't store that information right now

**Comment by amunn33** [comment]
I can double check this, but I think we are trying as much as possible up
have the budget sheets finalized before sending them out. This is also why
even if there is an error with the amount given, we correct in on the
following month rather than changing the previous one.

With that said, I don't think we should limit ourselves from that
possibility by attaching a doc. My main reason for suggesting that was a
backup if we didn't think we could change the URLs easily.
