### ISSUE TITLE
Trafficker Check

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#345]
# Story
Staff members go to page and type in the name or phone number of a suspected trafficker to see if they have shown up in our system before. Results are displayed that show them traffickers from our database with details similar to those that were typed in. 

# Requirements
- Create an end point that can take name and fuzzy match it against person objects in the database whose role is not victim (trafficker, broker, etc.).
- Create a similar end point that can take phone numbers and do partial matches.
- Create a permission that will be associated with this feature.

**Comment by amunn33** [comment]
@scrishel  is the "non-victim" role too broad? I wasn't sure if there would be other roles that we would want to exclude from this search but I wanted to make sure we were getting information from PBs as well.

**Comment by scrishel** [comment]
@amunn33 My plan was to exclude the persons identified as victims on the IRF and the victim identified in the VIF.  Guardians are currently not stored in the person table.  So that would leave the persons identified as traffickers on the IRF and the persons identified in the PBs on the VIFs.  Do we need to exclude some roles from the PBs?
